// This is a simplified version - the complete file would be generated by protoc
// For demonstration purposes, showing key methods only

package blog

import (
	proto "github.com/golang/protobuf/proto"
)

func init() {
	proto.RegisterType((*BlogInfo)(nil), "blog.BlogInfo")
	proto.RegisterType((*UserInfo)(nil), "blog.UserInfo")
	proto.RegisterType((*PublishBlogRequest)(nil), "blog.PublishBlogRequest")
	proto.RegisterType((*PublishBlogResponse)(nil), "blog.PublishBlogResponse")
	proto.RegisterType((*BlogListRequest)(nil), "blog.BlogListRequest")
	proto.RegisterType((*BlogListResponse)(nil), "blog.BlogListResponse")
	proto.RegisterType((*BlogDetailRequest)(nil), "blog.BlogDetailRequest")
	proto.RegisterType((*BlogDetailResponse)(nil), "blog.BlogDetailResponse")
	proto.RegisterType((*DeleteBlogRequest)(nil), "blog.DeleteBlogRequest")
	proto.RegisterType((*DeleteBlogResponse)(nil), "blog.DeleteBlogResponse")
	proto.RegisterType((*UpdateBlogRequest)(nil), "blog.UpdateBlogRequest")
	proto.RegisterType((*UpdateBlogResponse)(nil), "blog.UpdateBlogResponse")
	proto.RegisterType((*CategoryListResponse)(nil), "blog.CategoryListResponse")
	proto.RegisterType((*CategoryInfo)(nil), "blog.CategoryInfo")
	proto.RegisterType((*TagListResponse)(nil), "blog.TagListResponse")
	proto.RegisterType((*TagInfo)(nil), "blog.TagInfo")
}
